####################################################################################################
#	This helper module for dvr-yousee
#
#	Made by 
#	dane22....A Plex Community member
#
####################################################################################################

ChannelList = {
	"DR1":True,
	"DR2":True,
	"TV 2": True,
	"TV 2 Zulu":True,
	"TV 2 Charlie":True,
	"TV3":True,
	"TV3+":True,
	"Kanal 4":True,
	"Kanal 5":True,
	"Infokanalen":True,
	"TV3 Puls":True,
	"DK4":True,
	"YouSee Trailerkanal":True,
	"Kanal 5 HD":True,
	"DR3":True,
	"6'eren":True,
	"Nickelodeon":True,
	"Disney Channel":True,
	"Cartoon Network":True,
	"Disney XD":True,
	"TCM":True,
	"NatGeo Wild HD":True,
	"Eurosport":True,
	"TV3 SPORT 1":True,
	"TV3 SPORT 2":True,
	"EuroSport HD":True,
	"Animal Planet HD":True,
	"MTV Live HD":True,
	"Discovery Channel":True,
	"Animal Planet":True,
	"National Geographic":True,
	"DR1 Syn":True,
	"DR2 Syn":True,
	"DR3 Syn":True,
	"VH1":True,
	"TV 2 News":True,
	"Discovery HD Showcase":True,
	"BBC Brit":True,
	"BBC World":True,
	"CNN":True,
	"BBC HD":True,
	"TV4":True,
	"Sverige 1":True,
	"Sverige 2":True,
	"NRK2":True,
	"NRK1":True,
	"TV2 Norge":True,
	"24Nordjyske":True,
	"ARD":True,
	"ZDF":True,
	"NDR":True,
	"RTL":True,
	"Sat1":True,
	"Pro7":True,
	"VOX":True,
	"TV 2":True,
	"TLC Danmark":True,
	"TNT":True,
	"TLC HD Danmark":True,
	"TNT":True,
	"Nickelodeon HD":True,"6'eren HD":True,
	"Lokalt program":True,
	"Lokalt program":True,
	"Kanal Sport":True,
	"Prøvekanal":True,
	"ZDF HD":True,
	"DR Ultra":True,
	"OutDoor HD":True,
	"TV 2 Fri HD":True,
	"Euronews":True,
	"Ekstrakanalen":True,
	"Event HD":True,
	"CANAL+ First":True,
	"TV 2 SPORT HD":True,
	"Comedy Central HD":True,
	"Nat Geo People HD":True,
	"TV 2 Danmark HD":True,
	"History HD":True,
	"Canal 8 Sport":True,
	"Sverige 1 HD":True,
	"Showtime":True,
	"BBC Earth":True,
	"BBC Lifestyle":True,
	"Nick Jr.":True,"CNBC":True,
	"Viasat Nature Crime":True,
	"CANAL8 Sport":True,
	"CANAL9":True,"Discovery World":True,
	"Discovery Science":True,
	"Discovery Travel Living":True,
	"Eurosport 360 1":True,
	"Eurosport 360 2":True,
	"Eurosport 360 3":True,
	"Eurosport 360 4":True,
	"Eurosport 360 5":True,
	"Eurosport 360 6":True,
	"Eurosport 360 7":True,
	"MTV Rocks":True,
	"MTV Dance":True,
	"MTV Hits":True,
	"VH1 Classic":True,
	"CBS Reality":True,
	"Travel Channel":True,
	"Star!":True,
	"Dantoto Live":True,
	"Nat Geo Wild":True,
	"Motors TV":True,
	"MTV":True,
	"Disney Channel HD":True,
	"Arte":True,
	"Mezzo":True,
	"Kanal Sport HD":True,
	"TV 5":True,
	"Viasat History":True,
	"Viasat Explore":True,
	"H2":True,"Eurosport Danmark":True,"Viasat Hits":True,"Viasat Series":True,"Viasat Film Premiere":True,"Viasat Golf":True,"ESPN Classic Europe":True,"Eurosport 2":True,"ESPN America":True,"Viasat Comedy":True,"Bloomberg":True,"TV3 Sport 1 HD":True,"Canal 9 HD":True,"Investigation Discovery":True,"C More Emotion":True,"C More Golf":True,"C More Tennis":True,"C More First":True,"C More First":True,"C More Hits":True,"C More Kids":True,"C More Series":True,"C MORE Star":True,"Folketinget":True,"C More Hits HD":True,"Boomerang":True,"Toon Disney":True,"TV3+ HD":True,"EuroSport 2 HD":True,"Disney Junior":True,"Silver HD":True,
	"TV1000 Drama":True,"Viasat Film Action":True,
	"Viasat Fim Classic":True,"Viasat Film Drama":True,
	"Viasat Film Family":True,"Viasat Film":True,
	"Nordic":True,"Al Jazeera English":True,
	"3Sat":True,"France 2":True,"RaiUno":True,
	"TVE":True,"TV Pol":True,"Polsa2":True,
	"RTK 1":True,"Hayat TV":True,"BHT 1":True,"HRT1":True,"Pink+":True,"RTSsat":True,"RTCG":True,"Netflix":True,"Mezopotamya TV":True,"Roj TV":True,"TRT":True,
	"Euro Star":True,"Kanal7":True,
	"Euro D":True,"TGRT EU":True,
	"Lig TV":True,"ShowTV":True,
	"Trkmax":True,"STV":True,
	"ATV":True,
	"Kral TV":True,
	"MBC":True,
	"Al Jazeera":True,
	"EDTV":True,
	"Al Masriyah":True,
	"Al Aoula":True,
	"Art Movies":True,
	"Al Spo":True,
	"Iqraa":True,
	"Abu Dhabi TV":True,
	"Sony MAX":True,
	"SET":True,
	"AAG":True,
	"Geo TV":True,
	"Star Go":True,
	"Star PI":True,
	"CCTV 4":True,
	"Sony MAX":True,
	"Geo News":True,
	"Thai TV Global Netwo":True,
	"TV2 Nord":True,
	"TV Mid":True,
	"TV2 OJ":True,
	"TV Syd":True,
	"TV Fyn":True,
	"TV2 \u00d8stsj\u00e6lland":True,
	"Lorry":True,
	"TV2Bor":True,
	"TV2 \u00d8stjylland":True,
	"TV2 Syd":True,
	"TV2 Fyn":True,
	"TV2 Bornholm":True,
	"TV2 M":True,
	"TV2 N":True,
	"TV2 \u00d8":True,
	"HUSTLER tv":True,
	"Blue Hustler":True,
	"Playboy TV":True,
	"Hjørring Infokanal":True,
	"Kanalen Nord":True,
	"Kanalen Midt-Vest":True,
	"Kanal Veststjylland":True,
	"Kanal Syd":True,
	"Fynbo TV":True,
	"Kanalen \u00d8st":True,
	"Kanal Hovedstaden":True,
	"Kanalen Bornholm":True,
	"DR HD":True,
	"DR K":True,
	"DR Ramasjang":True,"DR Update"
}
